#include <stdio.h>
#define COLOR_BRIGHTRED  "\x1b[31;1m"
#define COLOR_RED	 "\x1b[31m"
#define COLOR_GREEN   	 "\x1b[32m"
#define COLOR_YELLOW  	 "\x1b[33m"
#define COLOR_BLUE    	 "\x1b[34m"
#define COLOR_MAGENTA 	 "\x1b[35m"
#define COLOR_CYAN    	 "\x1b[36m"
#define COLOR_GREY       "\x1b[11m"
#define COLOR_RESET   	 "\x1b[0m"
#define COLOR_WHITE      "\x1b[37m"
#define PWMASK           "\x1b[8m"
#define RESETMASK        "\x1b[0m"
#define LOCKCURSOR       "\x1b[s"

